name: Compile Paper

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - name: Install Python requirements
        run: pip install -r requirements.txt

      - name: Create contributor snippet
        run: python contributors.py
      
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: paper.tex
      
      - uses: actions/upload-artifact@v3
        with:
          name: Paper PDF
          path: paper.pdf
